AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: League API
Parameters:
  Stage:
    Description: The environment this application is deployed to (should be dev, staging
      or prod)
    Default: prod
    Type: String
Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
Resources:
  GetChampion:
    Type: AWS::Serverless::Function
    Properties:
      Handler: League_Api::League_Api.Functions.GetChampionFunction::Execute
      Runtime: dotnetcore2.1
      CodeUri: s3://anchoragewonder-deploys/83878f8a84e4b60592a3bfb9f433b8ad
      MemorySize: 2048
      Timeout: 30
      Role: null
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /champion/{name}
            Method: GET
  GetChampionEmpty:
    Type: AWS::Serverless::Function
    Properties:
      Handler: League_Api::League_Api.Functions.GetChampionFunction::Execute
      Runtime: dotnetcore2.1
      CodeUri: s3://anchoragewonder-deploys/83878f8a84e4b60592a3bfb9f433b8ad
      MemorySize: 2048
      Timeout: 30
      Role: null
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /champion/
            Method: GET
            Cors: '*'
  QuizPost:
    Type: AWS::Serverless::Function
    Properties:
      Handler: League_Api::League_Api.Functions.QuizRequestFunction::Execute
      Runtime: dotnetcore2.1
      CodeUri: s3://anchoragewonder-deploys/83878f8a84e4b60592a3bfb9f433b8ad
      MemorySize: 2048
      Timeout: 30
      Role: null
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /quizpost/
            Method: POST
            Cors: '*'
Outputs:
  ApiURL:
    Description: API endpoint URL
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: ServerlessRestApi
        - .execute-api.
        - Ref: AWS::Region
        - .amazonaws.com/
        - Ref: Stage
